-- TradingCRUD schema reference (H2 / PostgreSQL compatible)
-- See docs/資料庫設計.md for full documentation

CREATE TABLE IF NOT EXISTS app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(16)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_order_id VARCHAR(64)  NOT NULL UNIQUE,
    symbol          VARCHAR(20)  NOT NULL,
    side            VARCHAR(4)   NOT NULL,
    quantity        DECIMAL(18,8) NOT NULL,
    price           DECIMAL(18,8) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_symbol ON orders(symbol);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
